fix: build check

diff --git a/ci-cd/jenkins-pipeline/Jenkinsfile b/ci-cd/jenkins-pipeline/Jenkinsfile
--- a/ci-cd/jenkins-pipeline/Jenkinsfile
+++ b/ci-cd/jenkins-pipeline/Jenkinsfile
@@ -1,103 +1,201 @@
+/*
+    This is an example pipeline that implement full CI/CD for a simple static web site packed in a Docker image.
 
-podTemplate(label: 'mypod', serviceAccount: 'jenkins-ci', containers: [ 
-    containerTemplate(
-      name: 'docker', 
-      image: 'docker', 
-      command: 'cat', 
-      resourceRequestCpu: '100m',
-      resourceLimitCpu: '300m',
-      resourceRequestMemory: '300Mi',
-      resourceLimitMemory: '500Mi',
-      ttyEnabled: true
-    ),
-    containerTemplate(
-      name: 'kubectl', 
-      image: 'amaceog/kubectl',
-      resourceRequestCpu: '100m',
-      resourceLimitCpu: '300m',
-      resourceRequestMemory: '300Mi',
-      resourceLimitMemory: '500Mi', 
-      ttyEnabled: true, 
-      command: 'cat'
-    ),
-    containerTemplate(
-      name: 'helm', 
-      image: 'alpine/helm:2.14.0', 
-      resourceRequestCpu: '100m',
-      resourceLimitCpu: '300m',
-      resourceRequestMemory: '300Mi',
-      resourceLimitMemory: '500Mi',
-      ttyEnabled: true, 
-      command: 'cat'
-    )
-  ],
+    The pipeline is made up of 6 main steps
+    1. Git clone and setup
+    2. Build and local tests
+    3. Publish Docker and Helm
+    4. Deploy to dev and test
+    5. Deploy to staging and test
+    6. Optionally deploy to production and test
+ */
 
-  volumes: [
-    hostPathVolume(mountPath: '/var/run/docker.sock', hostPath: '/var/run/docker.sock'),
-    hostPathVolume(mountPath: '/usr/local/bin/helm', hostPath: '/usr/local/bin/helm')
-  ]
-  ) {
-    node('mypod') {
+/*
+    Create the kubernetes namespace
+ */
+def createNamespace (namespace) {
+    echo "Creating namespace ${namespace} if needed"
 
-        def REPOSITORY_URI = "gbxnga/nodejs-k8s-cicd"
-        def HELM_APP_NAME = "nodejs-app"
-        def HELM_CHART_DIRECTORY = "k8s/nodejs-k8s-cicd"
+    sh "[ ! -z \"\$(kubectl get ns ${namespace} -o name 2>/dev/null)\" ] || kubectl create ns ${namespace}"
+}
 
-        stage('Get latest version of code') {
-          checkout scm
+/*
+    Helm install
+ */
+def helmInstall (namespace, release) {
+    echo "Installing ${release} in ${namespace}"
+
+    script {
+        release = "${release}-${namespace}"
+        sh """
+            helm upgrade --install --namespace ${namespace} ${release} \
+                --set imagePullSecrets=${IMG_PULL_SECRET} \
+                --set image.repository=${DOCKER_REG}/${IMAGE_NAME},image.tag=${DOCKER_TAG} server/.deployment
+        """
+        sh "sleep 5"
+    }
+}
+
+/*
+    Helm delete (if exists)
+ */
+def helmDelete (namespace, release) {
+    echo "Deleting ${release} in ${namespace} if deployed"
+
+    script {
+        release = "${release}-${namespace}"
+        sh "[ -z \"\$(helm ls --short ${release} 2>/dev/null)\" ] || helm delete --purge ${release}"
+    }
+}
+
+/*
+    Run a curl against a given url
+ */
+def curlRun (url, out) {
+    echo "Running curl on ${url}"
+
+    script {
+        if (out.equals('')) {
+            out = 'http_code'
         }
-        stage('Check running containers') {
-            container('docker') {  
-                sh 'hostname'
-                sh 'hostname -i' 
-                sh 'docker ps'
-                sh 'ls'
-            }
-            container('kubectl') { 
-                sh 'kubectl get pods -n default'  
-            }
-            container('helm') { 
-                sh 'helm init --client-only --skip-refresh'
-                sh 'helm repo update'     
-            }
-        }  
+        echo "Getting ${out}"
+            def result = sh (
+                returnStdout: true,
+                script: "curl --output /dev/null --silent --connect-timeout 5 --max-time 5 --retry 5 --retry-delay 5 --retry-max-time 30 --write-out \"%{${out}}\" ${url}"
+        )
+        echo "Result (${out}): ${result}"
+    }
+}
 
-        stage('Build Image'){
-            container('docker'){
+/*
+    Test with a simple curl and check we get 200 back
+ */
+def curlTest (namespace, out) {
+    echo "Running tests in ${namespace}"
 
-              withCredentials([usernamePassword(credentialsId: 'docker-login', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
-                sh 'docker login --username="${USERNAME}" --password="${PASSWORD}"'
-                sh "docker build -t ${REPOSITORY_URI}:${BUILD_NUMBER} ."
-                sh 'docker image ls' 
-              } 
+    script {
+        if (out.equals('')) {
+            out = 'http_code'
+        }
+
+        // Get deployment's service IP
+        def svc_ip = sh (
+                returnStdout: true,
+                script: "kubectl get svc -n ${namespace} | grep ${ID} | awk '{print \$3}'"
+        )
+
+        if (svc_ip.equals('')) {
+            echo "ERROR: Getting service IP failed"
+            sh 'exit 1'
+        }
+
+        echo "svc_ip is ${svc_ip}"
+        url = 'http://' + svc_ip
+
+        curlRun (url, out)
+    }
+}
+
+/*
+    This is the main pipeline section with the stages of the CI/CD
+ */
+pipeline {
+
+    options {
+        // Build auto timeout
+        timeout(time: 60, unit: 'MINUTES')
+    }
+
+    // Some global default variables
+    environment {
+        IMAGE_NAME = 'kube-test-backend'
+        DOCKER_REPO = 'kube-test-backend'
+        DOCKER_REG = 'rajt17'
+        DOCKER_TAG = 'latest'
+        BUILD_DIR = 'server'
+        TEST_LOCAL_PORT = 8817
+        DEPLOY_PROD = false
+        PARAMETERS_FILE = "${JENKINS_HOME}/parameters.groovy"
+    }
+
+    parameters {
+        string (name: 'GIT_BRANCH',           defaultValue: 'master',  description: 'Git branch to build')
+        booleanParam (name: 'DEPLOY_TO_PROD', defaultValue: false,     description: 'If build and tests are good, proceed and deploy to production without manual approval')
+
+
+        // The commented out parameters are for optionally using them in the pipeline.
+        // In this example, the parameters are loaded from file ${JENKINS_HOME}/parameters.groovy later in the pipeline.
+        // The ${JENKINS_HOME}/parameters.groovy can be a mounted secrets file in your Jenkins container.
+/*
+        string (name: 'DOCKER_REG',       defaultValue: 'docker-artifactory.my',                   description: 'Docker registry')
+        string (name: 'DOCKER_TAG',       defaultValue: 'dev',                                     description: 'Docker tag')
+        string (name: 'DOCKER_USR',       defaultValue: 'admin',                                   description: 'Your helm repository user')
+        string (name: 'DOCKER_PSW',       defaultValue: 'password',                                description: 'Your helm repository password')
+        string (name: 'IMG_PULL_SECRET',  defaultValue: 'docker-reg-secret',                       description: 'The Kubernetes secret for the Docker registry (imagePullSecrets)')
+        string (name: 'HELM_REPO',        defaultValue: 'https://artifactory.my/artifactory/helm', description: 'Your helm repository')
+        string (name: 'HELM_USR',         defaultValue: 'admin',                                   description: 'Your helm repository user')
+        string (name: 'HELM_PSW',         defaultValue: 'password',                                description: 'Your helm repository password')
+*/
+    }
+
+    // In this example, all is built and run from the master
+    agent { node { label 'master' } }
+
+    // Pipeline stages
+    stages {
+
+        ////////// Step 1 //////////
+        stage('Git clone and setup') {
+            steps {
+                echo "Check out acme code"
+                git branch: "master",
+                        credentialsId: 'github-credentials',
+                        url: 'https://github.com/Rajatj17/webapp-and-backend-k8s-setup.git'
+
+                // Validate kubectl
+                sh "kubectl cluster-info"
+
+                echo 'JENKINS HOME: ${JENKINS_HOME}'
                 
-            }
-        } 
+                // Load Docker registry and Helm repository configurations from file
+                load "${JENKINS_HOME}/parameters.groovy"
 
-        stage('Testing') {
-            container('docker') { 
-              sh 'whoami'
-              sh 'hostname -i' 
-              sh "docker run ${REPOSITORY_URI}:${BUILD_NUMBER} npm run test "                 
+                echo "DOCKER_REG is ${DOCKER_REG}"
+                echo "HELM_REPO  is ${HELM_REPO}"
+
+                // Define a unique name for the tests container and helm release
+                script {
+                    branch = GIT_BRANCH.replaceAll('/', '-').replaceAll('\\*', '-')
+                    ID = "${IMAGE_NAME}-${DOCKER_TAG}-${branch}"
+
+                    echo "Global ID set to ${ID}"
+                }
             }
         }
 
-        stage('Push Image'){
-            container('docker'){
-              withCredentials([usernamePassword(credentialsId: 'docker-login', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
-                sh 'docker image ls'
-                sh "docker push ${REPOSITORY_URI}:${BUILD_NUMBER}"
-              }                 
+        ////////// Step 2 //////////
+        stage('Build and tests') {
+            steps {
+                sh  'ls'
+                sh 'cd server'
+                sh 'docker build -t ${DOCKER_REG}/${DOCKER_REPO}:${DOCKER_TAG} ${BUILD_DIR}'
             }
         }
 
-        stage('Deploy Image to k8s'){
-            container('helm'){
-                sh 'helm list'
-                sh "helm lint ./${HELM_CHART_DIRECTORY}"
-                sh "helm upgrade --wait --timeout 60 --set image.tag=${BUILD_NUMBER} ${HELM_APP_NAME} ./${HELM_CHART_DIRECTORY}"
-                sh "helm list | grep ${HELM_APP_NAME}"
+        ////////// Step 4 //////////
+        stage('Deploy to dev') {
+            steps {
+                script {
+                    namespace = 'jenkins-test'
+
+                    echo "Deploying application ${ID} to ${namespace} namespace"
+                    createNamespace (namespace)
+
+                    // Deploy with helm
+                    echo "Deploying"
+                    helmInstall(namespace, "${ID}")
+                }
             }
-        }      
+        }
     }
 }
